kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
  labels:
    placement: pacman-dr-placement
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 5Gi
